
hash_database = {
    [4] = {{name = "CRC-16", hashcat = "--", john = "--"}, {name = "FCS-16", hashcat = "--", john = "--"},
    },
    [6] = {{name = "CRC-24", hashcat = "--", john = "--"},
    },
    [8] = {
        { name = "Adler-32", hashcat = "--", john = "--" },
        { name = "CRC-32", hashcat = "--", john = "crc32" },
        { name = "CRC-32B", hashcat = "--", john = "--" },
        { name = "FNV-1-32", hashcat = "--", john = "--" },
        { name = "FNV-1a-32", hashcat = "--", john = "--" },
        { name = "Murmur3-32", hashcat = "--", john = "--" },
        { name = "FCS-32", hashcat = "--", john = "--" },
    },
    [16] = {
        { name = "LM", hashcat = "3000", john = "lm" },
        { name = "CRC-64", hashcat = "--", john = "--" },
        { name = "FNV-1-64", hashcat = "--", john = "--" },
        { name = "FNV-1a-64", hashcat = "--", john = "--" },
        { name = "Half-MD5", hashcat = "5100", john = "--" },
    },
    [32] = {
        { name = "MD5", hashcat = "0", john = "raw-md5" },
        { name = "NTLM", hashcat = "1000", john = "nt" },
        { name = "LM", hashcat = "3000", john = "lm" },
        { name = "MD4", hashcat = "900", john = "raw-md4" },
        {name = "Double MD5", hashcat = "2600", john = "--" },
        { name = "MD2", hashcat = "--", john = "md2" },
        { name = "RIPEMD-128", hashcat = "--", john = "ripemd-128" },
        { name = "BLAKE3-128", hashcat = "--", john = "--" },
    { name = "FNV-1-128", hashcat = "--", john = "--" },
        { name = "FNV-1-128", hashcat = "--", john = "--" },
        { name = "Murmur3-128", hashcat = "--", john = "--" },
        { name = "SNEFRU-128", hashcat = "--", john = "snefru-128" },
        { name = "Skein256-128", hashcat = "--", john = "--" },
        { name = "Skein512-128", hashcat = "--", john = "--" },
        { name = "Tiger-128", hashcat = "--", john = "--" },
        { name = "Tiger128-3", hashcat = "--", john = "--" },
        { name = "Haval-128", hashcat = "--", john = "haval-128-4" },
    },
    [40] = {
        { name = "SHA-1", hashcat = "100", john = "raw-sha1" },
        { name = "RIPEMD-160", hashcat = "6000", john = "ripemd-160" },
        {name = "Haval-160", hashcat = "", john = "" },
        { name = "Tiger-160", hashcat = "", john = "" },
        { name = "Tiger-160,3", hashcat = "", john = "" },
    },
     [48] = {
        { name = "Haval-192", hashcat = "", john = "" },
        { name = "Tiger-192", hashcat = "", john = "tiger" },
         { name = "Tiger-192-3", hashcat = "", john = "" },
    },
    [56] = {
        { name = "SHA-224", hashcat = "--", john = "raw-sha224" },
        { name = "SHA3-224", hashcat = "", john = "" },
         { name = "Haval-224", hashcat = "", john = "" },
        { name = "Whirlpool-224", hashcat = "", john = "" },
    },
    [64] = {
        { name = "SHA-256", hashcat = "1400", john = "raw-sha256" },
        { name = "SHA3-256", hashcat = "17600", john = "sha3-256" },
        { name = "BLAKE2s", hashcat = "--", john = "--" },
        { name = "BLAKE3-256", hashcat = "--", john = "--" },
        { name = "RIPEMD-256", hashcat = "--", john = "--" },
        { name = "Haval-256", hashcat = "--", john = "haval-256-3" },
        {name = "Gost", hashcat = "--", john = "--" },
        { name = "Gost-CryptoPro", hashcat = "--", john = "--" },
        { name = "SNEFRU-256", hashcat = "--", john = "snefru-256" },
        { name = "EDON-R-256", hashcat = "--", john = "--" },
    { name = "Skein256-256", hashcat = "--", john = "skein-256" },
        { name = "Skein512-256", hashcat = "--", john = "--" },
        { name = "Whirlpool-256", hashcat = "--", john = "--" },
    },
    [80] = {
        { name = "RIPEMD-320", hashcat = "--", john = "--" },
    },
    [96] = {
        { name = "SHA-384", hashcat = "10800", john = "raw-sha384" },
        { name = "SHA3-384", hashcat = "--", john = "--" },
         { name = "Whirlpool-384", hashcat = "--", john = "--" },
    },
    [102] = {
        { name = "Skein1024-408", hashcat = "", john = "" },
    },
    [128] = {
        { name = "SHA-512", hashcat = "1700", john = "raw-sha512" },
        { name = "SHA3-512", hashcat = "", john = "raw-keccak" },
        { name = "BLAKE2b", hashcat = "", john = "" },
         { name = "BLAKE3-512", hashcat = "", john = "" },
        { name = "Skein512-512", hashcat = "", john = "skein-512" },
        { name = "Whirlpool", hashcat = "6100", john = "whirlpool" },
        { name = "EDON-R-512", hashcat = "", john = "" },
         { name = "Whirlpool-1", hashcat = "", john = "" },
        { name = "Whirlpool-2", hashcat = "", john = "" },
    },
    [256] = {
        { name = "Skein512-1024", hashcat = "", john = "" },
        { name = "Skein1024-1024", hashcat = "", john = "" },
    },
}
